// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrnMAicsazfoTm3b-6345-LOLgf8RTd34',
    appId: '1:178922466892:web:b8de3084337e136b1fcee9',
    messagingSenderId: '178922466892',
    projectId: 'mobileuas-23b1b',
    authDomain: 'mobileuas-23b1b.firebaseapp.com',
    storageBucket: 'mobileuas-23b1b.appspot.com',
    measurementId: 'G-L4MY7PSJHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJe4OmvFiRXwbNA2Fyxi1xSZFhTTXjrT8',
    appId: '1:178922466892:android:2f2bec5bef4ea8771fcee9',
    messagingSenderId: '178922466892',
    projectId: 'mobileuas-23b1b',
    storageBucket: 'mobileuas-23b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamDn7V0EAZnHEmbx943JNSkyTYi5lJlk',
    appId: '1:178922466892:ios:df9dcfced690d2f91fcee9',
    messagingSenderId: '178922466892',
    projectId: 'mobileuas-23b1b',
    storageBucket: 'mobileuas-23b1b.appspot.com',
    iosBundleId: 'com.example.mobileiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamDn7V0EAZnHEmbx943JNSkyTYi5lJlk',
    appId: '1:178922466892:ios:2db56f470e2605371fcee9',
    messagingSenderId: '178922466892',
    projectId: 'mobileuas-23b1b',
    storageBucket: 'mobileuas-23b1b.appspot.com',
    iosBundleId: 'com.example.mobileiot.RunnerTests',
  );
}
